# Explicitly use Python 3.10.6
FROM python:3.11.5

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY . .

# Run the app
CMD ["gunicorn", "--bind", "0.0.0.0:5500", "app:app"]
